-- Initial Database Creation Script

CREATE TABLE IF NOT EXISTS TASK (
  TASK_ID BIGINT NOT NULL PRIMARY KEY,
  USER_ID BIGINT NOT NULL,
  TASK_NAME VARCHAR(100) NOT NULL,
  DESCRIPTION VARCHAR(2000),
  DATE_TIME TIMESTAMP,
  STATUS VARCHAR(20),
  CREATION_DATE TIMESTAMP,
  LAST_UPDATE_DATE TIMESTAMP,
  VERSION BIGINT NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS TASK_U1 ON TASK(TASK_ID);
CREATE INDEX IF NOT EXISTS TASK_N1 ON TASK(DATE_TIME, STATUS);
CREATE INDEX IF NOT EXISTS TASK_N2 ON TASK(USER_ID);

CREATE TABLE IF NOT EXISTS USER (
  USER_ID BIGINT NOT NULL PRIMARY KEY,
  USER_NAME VARCHAR(100) NOT NULL,
  FIRST_NAME VARCHAR(100),
  LAST_NAME VARCHAR(100),
  CREATION_DATE TIMESTAMP,
  LAST_UPDATE_DATE TIMESTAMP,
  VERSION BIGINT NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS USER_U1 ON USER(USER_ID);
CREATE UNIQUE INDEX IF NOT EXISTS USER_U2 ON USER(USER_NAME);

CREATE SEQUENCE HIBERNATE_SEQUENCE START WITH 1 INCREMENT BY 1;